RafaMarket/ViewModels/RoleView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RafaMarket.ViewModels
{
    public class RoleView
    {
        public string RoleId { get; set; }

        public string Name { get; set; }


    }
}

RafaMarket/ViewModels/UserView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RafaMarket.ViewModels
{
    public class UserView
    {
        public string UserId { get; set; }

        public string Name { get; set; }

        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public RoleView Role { get; set; }

        public List<RoleView> Roles { get; set; }


    }
}

RafaMarket/Controllers/UsersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using RafaMarket.Helpers;
using RafaMarket.Models;
using RafaMarket.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace RafaMarket.Controllers
{
    public class UsersController : Controller
    {
        // Ligação á Base de dados através do contexte Default
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Users
        // Mostrar lista de utilizadores
        public ActionResult Index()
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

            // Lista de Users existentes
            var users = userManager.Users.ToList();

            // Lista do tipo UserView
            var usersView = new List<UserView>();

            // Passar para a View
            foreach (var user in users)
            {
                var userView = new UserView
                {
                    Email = user.Email,
                    Name = user.UserName,
                    UserId = user.Id
                };

                usersView.Add(userView);
            }

            return View(usersView);
        }

        // GET: Roles/5
        // Mostrar as roles atribuidas ao utilizador
        public ActionResult Roles (string userID)
        {
            // Verifica se userID sem vazio
            if(string.IsNullOrEmpty(userID))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Ligação aos Users
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            // ligção aos Roles
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));

            var roles = roleManager.Roles.ToList();
            var users = userManager.Users.ToList();

            // Procurar o user
            var user = users.Find(u => u.Id == userID);

            // Verifica se userID existe
            if(user == null)
            {
                return HttpNotFound();
            }

            // Lista para a RoleView
            var rolesView = new List<RoleView>();

            // carregar a RoleView com as permissõs dos user encontrado
            foreach (var item in user.Roles)
            {
                // Procurar as roles do user
                var role = roles.Find(r => r.Id == item.RoleId);

                var roleView = new RoleView
                {
                    RoleId = role.Id,
                    Name = role.Name
                };

                rolesView.Add(roleView);
            }

            // Criar a View com os dados
            var userView = new UserView
            {
                Email = user.Email,
                Name = user.UserName,
                UserId = user.Id,
                Roles = rolesView
            };

            return View(userView);

        }

        // GET: AddRole?userID=5
        public ActionResult AddRole (string userID)
        {
            if (string.IsNullOrEmpty(userID))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var users = userManager.Users.ToList();
            var user = users.Find(u => u.Id == userID);

            if (user == null)
            {
                return HttpNotFound();
            }

            var userView = new UserView
            {
                Email = user.Email,
                Name = user.UserName,
                UserId = user.Id
            };

            ViewBag.RoleId = new SelectList(CombosHelper.GetRoles() , "Id", "Name");

            return View(userView);
        }

        // POST: AddRole?userID=5
        [HttpPost]
        public ActionResult AddRole(string userID, FormCollection form)
        {
            var roleID = Request["RoleId"];

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var users = userManager.Users.ToList();
            var user = users.Find(u => u.Id == userID);

            var userView = new UserView
            {
                Email = user.Email,
                Name = user.UserName,
                UserId = user.Id
            };

            // Quando o Model é um viewModel temos que fazer as validações na action, porque não se está a utilizar o identety
            if (string.IsNullOrEmpty(roleID))
            {
                ViewBag.Error = "Tem que selecionar uma permissão";
                ViewBag.RoleId = new SelectList(CombosHelper.GetRoles(), "Id", "Name");
                return View(userView);
            }

            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            var roles = roleManager.Roles.ToList();
            var role = roles.Find(r => r.Id == roleID);

            // Verificar se user já tem a permissão e adicionar na tabela
            if (!userManager.IsInRole(userID, role.Name))
            {
                userManager.AddToRole(userID, role.Name);
            }

            // Montar a RoleView
            var rolesView = new List<RoleView>();
                        
            foreach (var item in user.Roles)
            {
                role = roles.Find(r => r.Id == item.RoleId);
                var roleView = new RoleView
                {
                    Name = role.Name,
                    RoleId = role.Id
                };

                rolesView.Add(roleView);
            }

            // Montar a UserView
            userView = new UserView
            {
                Email = user.Email,
                Name = user.UserName,
                Roles = rolesView,
                UserId = user.Id
            };
            

            return View("Roles", userView);
        }

        public ActionResult Delete (string userID, string roleID)
        {
            if (string.IsNullOrEmpty(userID) || string.IsNullOrEmpty(roleID))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            var role = roleManager.Roles.ToList().Find(r => r.Id == roleID);

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var user = userManager.Users.ToList().Find(u => u.Id == userID);

            // Verificar se utilizador tem a role
            if (userManager.IsInRole(user.Id, role.Name))
            {
                // apagar a role do user
                userManager.RemoveFromRole(user.Id, role.Name);
            }

            // Preparar a View
            var users = userManager.Users.ToList();
            var roles = roleManager.Roles.ToList();

            var rolesView = new List<RoleView>();

            foreach (var item in user.Roles)
            {
                role = roles.Find(r => r.Id == item.RoleId);
                var roleView = new RoleView
                {
                    Name = role.Name,
                    RoleId = role.Id
                };

                rolesView.Add(roleView);
            }

            var userView = new UserView
            {
                Email = user.Email,
                Name = user.UserName,
                Roles = rolesView,
                UserId = user.Id
            };

            return View("Roles", userView);

        }

        /// <summary>
        /// Metodo que é utilizado para fechar a ligação depois de utilizar algum dos metodos no contrulado
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RafaMarket/Views/Users/AddRole.cshtml
@model RafaMarket.ViewModels.UserView

@{
    ViewBag.Title = "Adicionar permissão";
}

<h2>Adicionar permissão para o utilizador: @Model.Name</h2>
<h3>@ViewBag.Error</h3>

<!-- Passamos no form tambem o userID -->
@using (Html.BeginForm("AddRole", "Users", new { userID = Model.UserId}, FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <div class="form-group">
        @Html.LabelFor(model => model.Role.RoleId, "RoleId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("RoleId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Role.RoleId, "", new { @class = "text-danger" })
        </div>
    </div>

    <br />
    <br />
    @Html.ActionLink("Voltar para utilizador", "Roles", new { userID = Model.UserId }, new { @class = "btn btn-info " })
    <input type="submit" value="Adiciona Permissão" class="btn btn-success" />

</div>
}

RafaMarket/Views/Users/Index.cshtml
@model IEnumerable<RafaMarket.ViewModels.UserView>

@{
    ViewBag.Title = "Gestor de permissões";
}

<h2>Gestor de permissões</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>
    @foreach(var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.ActionLink("Roles", "Roles", new { UserId = item.UserId})
        </td>
    </tr>
    }
</table>

RafaMarket/Views/Users/Roles.cshtml
@model RafaMarket.ViewModels.UserView

@{
    ViewBag.Title = "Permissões";
}

<h2>Permissões para o utilizador: @Model.Name</h2>

<p>
    @Html.ActionLink("Adicionar Permissão", "AddRole", new { userid = Model.UserId }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-info" })
</p>

<table class="table">
    @for (int i = 0; i < Model.Roles.Count; i++)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelitem => Model.Roles[i].Name)
            </td>
            <td>
                @Html.ActionLink("Apagar", "Delete", new { userID = Model.UserId, roleID = Model.Roles[i].RoleId })
            </td>
        </tr>
    }



</table>